{% set name = "pyproject_hooks" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_hooks-{{ version }}.tar.gz
  sha256: 1e859bd5c40fae9448642dd871adf459e5e2084186e8d2c2a79a824c970da1f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2, <4
  run:
    - python >={{ python_min }}
    - tomli >=1.1.0

test:
  imports:
    - pyproject_hooks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyproject_hooks/
  summary: Wrappers to call pyproject.toml-based build backend hooks.
  dev_url: https://github.com/pypa/pyproject-hooks
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
