{% set name = "pyproject_hooks" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyproject_hooks-{{ version }}.tar.gz
  sha256: defda19b854fa0d3bd4f76ea4ddcba8abd7dcfcdd585a6690ade050744fc5f43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2, <4
  run:
    - python >={{ python_min }}
    - tomli >=1.1.0

test:
  imports:
    - pyproject_hooks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyproject_hooks/
  summary: Wrappers to call pyproject.toml-based build backend hooks.
  dev_url: https://github.com/pypa/pyproject-hooks
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
