{% set name = "pyproject_hooks" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyproject_hooks-{{ version }}.tar.gz
  sha256: 4b37730834edbd6bd37f26ece6b44802fb1c1ee2ece0e54ddff8bfc06db86965

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.2, <4
  run:
    - python >=3.7
    - tomli >=1.1.0

test:
  imports:
    - pyproject_hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyproject_hooks/
  summary: Wrappers to call pyproject.toml-based build backend hooks.
  dev_url: https://github.com/pypa/pyproject-hooks
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
